---
- name: Check for passwords being set
  ansible.builtin.stat:
    path: "{{ elasticstack_initial_passwords }}"
  delegate_to: "{{ elasticstack_ca_host }}"
  register: elasticsearch_passwords_file

- name: Fetch Elastic password # noqa: risky-shell-pipe
  ansible.builtin.shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    grep "PASSWORD elastic" {{ elasticstack_initial_passwords }} |
    awk {' print $4 '}
  register: elasticstack_password
  changed_when: false
  no_log: "{{ elasticstack_no_log }}"
  delegate_to: "{{ elasticstack_ca_host }}"
  when: elasticsearch_passwords_file.stat.exists | bool
