---

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Set target version to Elasticsearch on CA host
  ansible.builtin.set_fact:
    elasticstack_version: "{{ ansible_facts.packages['elasticsearch'].version }}"
  delegate_to: "{{ elasticstack_ca }}"
  when:
    - ansible_facts.packages['elasticsearch'].version is defined
    - if elasticstack_version is undefined
