---

- name: Check for passwords being set
  ansible.builtin.stat:
    path: "{{ elasticstack_initial_passwords }}"
  delegate_to: "{{ elasticstack_ca_host | default(omit, true) }}"
  run_once: true
  register: elasticsearch_passwords_file

- name: Fetch Elastic password # noqa: risky-shell-pipe
  ansible.builtin.shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    grep "PASSWORD elastic" {{ elasticstack_initial_passwords }} |
    awk {' print $4 '}
  register: __elasticstack_password_fetch
  run_once: true
  changed_when: false
  no_log: "{{ elasticstack_no_log }}"
  delegate_to: "{{ elasticstack_ca_host | default(omit, true) }}"
  when: elasticsearch_passwords_file.stat.exists | bool

- name: Persist the elastic password as a fact for all roles
  ansible.builtin.set_fact:
    __elasticstack_password: "{{ __elasticstack_password_fetch.stdout }}"
  when: __elasticstack_password_fetch.stdout is defined
