---

- name: Include OS specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Set elasticstack_ca variable if not already done by user
  ansible.builtin.set_fact:
    elasticstack_ca: "{{ groups['elasticsearch'][0] }}"
  when:
    - elasticstack_ca is undefined
    - groups['elasticsearch'][0] is defined

- name: Set versions for components
  ansible.builtin.import_tasks: elasticstack_versions.yml

- name: Set elasticstack_globals_set for other roles to skip this role
  ansible.builtin.set_fact:
    elasticstack_globals_set: true
