---
# The workaround for arbitrarily named role directory is important because the git repo has one name and the role within it another
# Found at: https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  collections:
    - NETWAYS.elasticstack
  hosts: all
  vars:
    elasticsearch_enable: false
    elasticsearch_security: false
    elastic_stack_full_stack: false
    elasticsearch_jna_workaround: true
    elasticsearch_disable_systemcallfilterchecks: true
    elastic_release: "{{ lookup('env', 'ELASTIC_RELEASE') }}"
  tasks:
    - name: Include Elastics repos role
      include_role:
        name: repos
    - name: Include Elasticsearch
      include_role:
        name: elasticsearch
