---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: "elasticsearch_default1-${MOLECULE_DISTRO:-debian12}"
    groups:
      - elasticsearch
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: "elasticsearch_default2-${MOLECULE_DISTRO:-debian12}"
    groups:
      - elasticsearch
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      elasticsearch_default1-rockylinux8:
        ansible_python_interpreter: /usr/bin/python3.9
      elasticsearch_default2-rockylinux8:
        ansible_python_interpreter: /usr/bin/python3.9
verifier:
  name: ansible
