---

- name: Include global role
  ansible.builtin.import_role:
    name: netways.elasticstack.elasticstack

- name: Import RedHat tasks
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Import Debian tasks
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Import SuSE tasks
  ansible.builtin.import_tasks: suse.yml
  when: ansible_os_family|lower == 'suse'
