---

- name: Check for versions
  ansible.builtin.fail:
    msg: "No OSS versions later than 7 are available"
  when:
    - elasticstack_release | int > 7
    - elasticstack_variant == "oss"

- name: Import RedHat tasks
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Import Debian tasks
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Import SuSE tasks
  import_tasks: suse.yml
  when: ansible_os_family|lower == 'suse'
