---
# Import Elastic Vault
- name: Vault Elastic management user from filelocation 
  include_vars:
    file: "{{ role_path }}/vars/secret_vars.yml"
  no_log: true

# Import User Vault
- name: Vault Include users secrets from filelocation
  include_vars:
    file: "{{ role_path }}{{elastic_users_add_path}}"
    name: users
  no_log: true

- name: Create new users
  ansible.builtin.include_tasks: users-create-users.yml

- name: Get index size
  ansible.builtin.include_tasks: index-get-size.yml

- name: Delete users
  ansible.builtin.include_tasks: users-delete-users.yml

- name: Get current users
  ansible.builtin.include_tasks: users-get-users.yml

- name: Get current roles
  ansible.builtin.include_tasks: roles-get-roles.yml

- name: Delete roles
  ansible.builtin.include_tasks: roles-delete-roles.yml

- name: Add roles
  ansible.builtin.include_tasks: roles-add-roles.yml
