---

- name: Include Elasticsearch_User Ansible vault secrets
  include_vars:
    file: "{{ role_path }}/vars/secret_vars.yml"

- name: Include User vault secrets
  include_vars:
    file: "{{ role_path }}/files/users.yml"

- name: Include users from users.yml
  include_vars:
    file: "{{ role_path }}/files/users.yml"
    name: users

#- name: Create new users
#  ansible.builtin.include_tasks: users-create-users.yml
#
#- name: Get index size
#  ansible.builtin.include_tasks: index-get-size.yml
#
#- name: Delete users
#  ansible.builtin.include_tasks: users-delete-users.yml
#
#- name: Get current users
#  ansible.builtin.include_tasks: users-get-users.yml

- name: Get current roles
  ansible.builtin.include_tasks: roles-get-roles.yml

- name: Edit roles
  ansible.builtin.include_tasks: roles-edit-roles.yml