---

- name: Include Ansible vault secrets
  include_vars:
    file: "{{ role_path }}/vars/secret_vars.yml"

- name: Include users from users.yml
  include_vars:
    file: "{{ role_path }}/files/users.yml"
    name: users

- name: Get current users
  ansible.builtin.include_tasks: users-get-users.yml

- name: Create new users
  ansible.builtin.include_tasks: users-create-users.yml

- name: Delete users
  ansible.builtin.include_tasks: users-delete-users.yml


#bin/elasticsearch-users list