---

- name: Include elastic management iser from vars/secret_vars.yml 
  include_vars:
    file: "{{ role_path }}/vars/secret_vars.yml"
  no_log: true

- name: Include users secrets from files/users.yml
  include_vars:
    file: "{{ role_path }}/files/users.yml"
    name: users
  no_log: true

- name: Create new users
  ansible.builtin.include_tasks: users-create-users.yml

- name: Get index size
  ansible.builtin.include_tasks: index-get-size.yml

- name: Delete users
  ansible.builtin.include_tasks: users-delete-users.yml

- name: Get current users
  ansible.builtin.include_tasks: users-get-users.yml

- name: Get current roles
  ansible.builtin.include_tasks: roles-get-roles.yml

- name: Edit roles
  ansible.builtin.include_tasks: roles-edit-roles.yml