---
- name: Get role information from Elasticsearch
  uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_host }}:{{ elasticsearch_port }}/_security/role/"
    method: GET
    user: "{{ elastic_username }}"
    password: "{{ elastic_password }}"
    return_content: yes
    validate_certs: no
  register: role_info

- name: Debug - Print role information
  debug:
    msg: "Role Information: {{ role_info }}"

# Information stored output

- name: Write Elasticsearch Roles and Role Information to File on Ansible-Controller's home directory
  delegate_to: localhost
  run_once: true
  become: false
  copy:
    content: |
      Elasticsearch Roles:
      ---------------------
      {% for role_name, role_data in role_info.json.items() %}
      Role: {{ role_name }}
      - Cluster Privileges: {{ role_data.cluster }}
      - Index Privileges:
        {% for index_privilege in role_data.indices %}
          - Index: {{ index_privilege.names | join(", ") }}
            Privileges: {{ index_privilege.privileges | join(", ") }}
        {% endfor %}
      - Run As: {{ role_data.run_as | join(", ") }}
      ------------------------------
      {% endfor %}
    dest: "{{ lookup('env', 'HOME') }}/elasticsearch_roles_and_info.txt"
    force: yes
