---

- name: Update Roles in Elasticsearch
  uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_host }}:{{ elasticsearch_port }}/_security/role/{{ item.key }}"
    method: PUT
    user: "{{ elastic_username }}"
    password: "{{ elastic_password }}"
    body: "{{ item.value | to_json }}"
    headers:
      Content-Type: "application/json"
    validate_certs: no
    status_code: 201,200 # 201 means created, 200 means updated
  with_dict:
    # Test Role 1
    logstash_custom_admin:
      cluster: ['manage_logstash_pipelines']
      indices:
        - names: ['.logstash*']
          privileges: ['create', 'delete', 'index', 'manage', 'read']
      metadata: {} # Removed _reserved
      run_as: []
    # Test Role 2
    bugs_bunny:
      cluster: ['manage_logstash_pipelines']
      indices:
        - names: ['.logstash*']
          privileges: ['index', 'manage', 'read']
      metadata: {} # Removed _reserved
      run_as: []
    # Test Role 3
    editor_like:
      applications:
        - application: "kibana-.kibana"
          privileges: ["all"]
          resources: ["*"]
      cluster: []
      indices:
        - allow_restricted_indices: false
          names: ['/~(([.]|ilm-history-).*)/']
          privileges: ['read', 'view_index_metadata']
        - allow_restricted_indices: false
          names: ['observability-annotations']
          privileges: ['read', 'view_index_metadata', 'write']
      metadata: {}  # Removed _reserved or any other metadata that starts with an underscore
      run_as: []