---

- name: Include roles from {{elastic_roles_add_path}}
  include_vars:
    file: "{{ role_path }}{{elastic_roles_add_path}}"
    name: roles

- name: Update Roles in Elasticsearch
  uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_host }}:{{ elasticsearch_port }}/_security/role/{{ item.key }}"
    method: PUT
    user: "{{ elastic_username }}"
    password: "{{ elastic_password }}"
    body: "{{ item.value | to_json }}"
    headers:
      Content-Type: "application/json"
    validate_certs: no
    status_code: 201,200
  with_dict: "{{ roles.roles }}"
