---
- name: Prepare
  hosts: all
  tasks:
    - name: Install packages for Debian
       ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - git
        update_cache: yes

    #- name: Create Logstash directory
    #  ansible.builtin.file:
    #    path: /etc/logstash
    #    owner: root
    #    group: root
    #    mode: 0755
    #    state: directory

    #- name: Create Logstash conf.d
    #  ansible.builtin.file:
    #    path: /etc/logstash/conf.d
    #    owner: root
    #    group: root
    #    mode: 0755
    #    state: directory

    #- name: Create Logstash syslog pipeline
    #  ansible.builtin.file:
    #    path: /etc/logstash/conf.d/syslog
    #    owner: root
    #    group: root
    #    mode: 0755
    #    state: directory

    #- name: Create Syslog input
    #  ansible.builtin.copy:
    #    dest: /etc/logstash/conf.d/syslog/input.conf
    #    content: >
    #      "input {
    #         redis {
    #           key => input
    #           host => localhost
    #           data_type => list
    #         }
    #       }
    #      "

    #- name: Create Syslog output
    #  ansible.builtin.copy:
    #    dest: /etc/logstash/conf.d/syslog/output.conf
    #    content: >
    #      "output {
    #         redis {
    #           key => input
    #           host => localhost
    #           data_type => list
    #         }
    #       }
    #      "
