---
# This is an example playbook to execute Ansible tests.

- name: Check if Logstash configuration does what it should
  hosts: all
  vars:
    elasticstack_beats_port: 5044
  tasks:
  - name: Run syntax check
    ansible.builtin.command: "/usr/share/logstash/bin/logstash --path.settings=/etc/logstash -t"
    changed_when: false

  - name: Check for open port tcp {{ elasticstack_beats_port }}
    ansible.builtin.wait_for:
      port: "{{ elasticstack_beats_port }}"

  - name: Create Syslog input
    ansible.builtin.copy:
      dest: /etc/logstash/conf.d/syslog/input.conf
      content: >
        "input {
           redis {
             key => input
             host => localhost
             data_type => list
           }
         }
        "

  - name: Create Syslog output
    ansible.builtin.copy:
      dest: /etc/logstash/conf.d/syslog/output.conf
      content: >
        "output {
           redis {
             key => input
             host => localhost
             data_type => list
           }
         }
        "
  - name: Update Pipeline code
    ansible.builtin.git:
      repo: https://github.com/widhalmt/syslog-logstash-pipeline.git
      dest: /etc/logstash/conf.d/syslog/
      version: master
