namespace: netways
name: elasticstack
version: 1.0.0
readme: README.md
authors:
  - Alexander Stoll <alexander.stoll@netways.de>
  - Markus Frosch <markus.frosch@netways.de>
  - Patrick Dolinic <patrick.dolinic@netways.de>
  - Thilo Wening <thilo.wening@netways.de>
  - Thomas Widhalm <thomas.widhalm@netways.de>
description: This collection installs and configures components from the Elastic Stack. Every role can be used standalone or in combination with other roles.
license:
  - GPL-3.0
license_file: 'LICENSE'
tags:
  - elastic
  - elasticsearch
  - kibana
  - logstash
  - beat
  - metricbeat
  - filebeat
  - monitoring
dependencies:
  "community.general": "*"
repository: https://github.com/netways/ansible-collection-elasticstack
documentation: https://github.com/netways/ansible-collection-elasticstack/README.md
homepage: https://www.netways.de
issues: https://github.com/netways/ansible-collection-elasticstack/issues
build_ignore:
  - .github
  - .cache
  - molecule
  - .gitignore
  - daemon.json
  - .mailmap
  - '*.tar.gz'
  - 'venv*'
