---
# handlers file for logstash
- name: Restart Logstash
  ansible.builtin.service:
    name: logstash
    state: restarted
    daemon-reload: true
  when:
    - logstash_enable | bool
    - not logstash_freshstart.changed | bool

- name: Restart Logstash noauto
  ansible.builtin.service:
    name: logstash
    state: restarted
    daemon-reload: true
  when: not logstash_config_autoreload and logstash_enable | bool
