---
- name: Fetch certificate from ca host to master
  fetch: src={{ elastic_ca_dir }}/{{ ansible_hostname }}.p12 dest=/tmp/ flat=yes
  delegate_to: "{{ elasticsearch_ca }}"

- name: Create certificate directory
  file:
    state: directory
    path: /etc/logstash/certs
    owner: root
    group: logstash
    mode: 0750

- name: Copy the certificate to actual node
  copy: src=/tmp/{{ ansible_hostname }}.p12 dest=/etc/logstash/certs/cert.p12
  notify:
    - Restart Logstash

- name: Fetch ca certificate from ca host to master
  fetch: src={{ elastic_ca_dir }}/ca.crt dest=/tmp/ flat=yes
  delegate_to: "{{ elasticsearch_ca }}"
- name: Copy the ca certificate to actual node
  copy:
    src: /tmp/ca.crt
    dest: /etc/logstash/certs
    owner: root
    group: logstash
    mode: 0640
  notify:
    Restart Logstash

