---

- name: Check for versions
  ansible.builtin.fail:
    msg: "No OSS versions later than 7 are available"
  when:
    - elastic_release > 7
    - elastic_variant == "oss"

- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'
