---
- name: Ensure Logstash is installed
  package:
    name: logstash

- name: Configure Logstash
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
    owner: root
    group: root
    mode: 0644
    backup: "{{ logstash_config_backup }}"
  notify:
    - Restart Logstash
  when: logstash_manage_yaml | bool

- name: Create Logstash pipeline directories
  file:
    path: "/etc/logstash/conf.d/{{ logstash_pipelines[item].name }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ logstash_pipelines }}"
  when: logstash_manage_pipelines | bool

- name: Check out pipeline configuration
  git:
    repo: "{{ logstash_pipelines[item].source }}"
    dest: "/etc/logstash/conf.d/{{ logstash_pipelines[item].name }}"
    version: master
  with_items: "{{ logstash_pipelines }}"
  when: logstash_manage_pipelines | bool
  notify:
    - Restart Logstash noauto

- name: Create directory for default Elasticsearch output pipeline
  file:
    path: "/etc/logstash/conf.d/ansible-forwarder"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: logstash_elasticsearch_output | bool

- name: Create default Elasticsearch output pipeline inputs
  template:
    src: redis-input.conf.j2
    dest: "/etc/logstash/conf.d/ansible-forwarder/input.conf"
    owner: root
    group: root
    mode: 0644
  when: logstash_elasticsearch_output | bool
  notify:
    - Restart Logstash noauto

- name: Create default Elasticsearch output pipeline output
  template:
    src: elasticsearch-output.conf.j2
    dest: "/etc/logstash/conf.d/ansible-forwarder/output.conf"
    owner: root
    group: root
    mode: 0644
  when: logstash_elasticsearch_output | bool
  notify:
    - Restart Logstash noauto

- name: Configure Logstash pipelines
  template:
    src: pipelines.yml.j2
    dest: /etc/logstash/pipelines.yml
    owner: root
    group: root
    mode: 0644
    backup: "{{ logstash_config_backup }}"
  when: logstash_manage_pipelines | bool

- import_tasks: logstash-security.yml
  when: elastic_stack_full_stack | bool and logstash_security | bool
  tags:
    - security

- name: Start Logstash
  service:
    name: logstash
    state: started
    enabled: yes
  when: logstash_enable | bool
