---
# tasks file for kibana
- name: install Kibana
  package:
    name: kibana
- import_tasks: kibana-security.yml
  when: elasticsearch_http_security is defined and elasticsearch_http_security | bool
  tags:
    - security
- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644
    backup: "{{ kibana_config_backup }}"
  notify:
    - Restart Kibana
  when: kibana_manage_yaml | bool
- name: start Kibana
  service:
    name: kibana
    state: started
# the following is useful when running tests or extra tasks that need to have Kibana running
- name: Wait for Kibana to start
  wait_for:
    host: localhost
    port: 5601
