---
- name: Install openssl if security is activated
  package:
    name: openssl
  when: elasticsearch_security | bool

# the following should be done by the rpm but failed with 7.4
- name: set ulimits for Elasticsearch
  pam_limits:
    limit_item: nofile
    domain: elasticsearch
    value: 65535
    limit_type: hard

- name: Ensure Elasticsearch is installed
  package:
    name: elasticsearch
  when: elastic_variant == "elastic"

- name: Ensure Elasticsearch OSS is installed
  package:
    name: elasticsearch-oss
  when: elastic_variant == "oss"

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
    backup: "{{ elasticsearch_config_backup }}"
  notify:
    - Restart Elasticsearch
  when: elasticsearch_manage_yaml | bool

- import_tasks: elasticsearch-security.yml
  when:
    - elasticsearch_security | bool
    - elastic_variant == "elastic"
  tags:
    - security

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
  when: elasticsearch_enable | bool

- name: Show hint about passwords
  debug:
    msg: "Remember, your temporary passwords can be found on {{ elasticsearch_ca }} in {{ elastic_initial_passwords }}"
  when:
    - elasticsearch_security | bool
    - elastic_variant == "elastic"
