---
- name: Check-set-parameters
  ansible.builtin.include_tasks: elasticsearch-parameters.yml

- name: Include OS specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Set common password for common certificates
  set_fact:
    elasticsearch_tls_key_passphrase: "{{ elastic_cert_pass }}"
  when:
  - elastic_cert_pass is defined

- name: Install openssl if security is activated
  package:
    name: openssl
  when: elasticsearch_security | bool

# the following should be done by the rpm but failed with 7.4
- name: Set ulimits for Elasticsearch
  community.general.system.pam_limits:
    limit_item: nofile
    domain: elasticsearch
    value: 65535
    limit_type: hard

- name: Ensure Elasticsearch is installed
  package:
    name: elasticsearch
  when: elastic_variant == "elastic"

- name: Ensure Elasticsearch OSS is installed
  package:
    name: elasticsearch-oss
  when: elastic_variant == "oss"

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
    backup: "{{ elasticsearch_config_backup }}"
  notify:
    - Restart Elasticsearch
  when: elasticsearch_manage_yaml | bool

- name: Import Tasks elasticsearch-security.yml
  import_tasks: elasticsearch-security.yml
  when:
    - elasticsearch_security | bool
    - elastic_variant == "elastic"
  tags:
    - security
    - certificates

- name: Create Elasticsearch data directory
  file:
    path: "{{ elasticsearch_datapath }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: "2750"
  when: elasticsearch_create_datapath | bool

- name: Activate JNA workaround (see README.md)
  lineinfile:
    path: "{{ elasticsearch_sysconfig_file }}"
    regexp: 'ES_JAVA_OPTS='
    line: 'ES_JAVA_OPTS="-Djna.tmpdir={{ elasticsearch_datapath }}/tmp"'
  notify:
    - Restart Elasticsearch
  when: elasticsearch_jna_workaround | bool

- name: Set initial heap
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms'
    line: '-Xms{{ elasticsearch_heap }}g'
  notify:
    - Restart Elasticsearch

- name: Set maximum heap
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx'
    line: '-Xmx{{ elasticsearch_heap }}g'
  notify:
    - Restart Elasticsearch

- name: Show Info about heap
  debug:
    msg: "Using {{ elasticsearch_heap * 1024 }} of {{ ansible_memtotal_mb }} MB as heap for Elasticsearch"

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
  when: elasticsearch_enable | bool
  failed_when: false

- name: Show hint about passwords
  debug:
    msg: "Remember, your temporary passwords can be found on {{ elasticsearch_ca }} in {{ elastic_initial_passwords }}"
  when:
    - elasticsearch_security | bool
    - elastic_variant == "elastic"
