---
- name: Set elasticsearch_ca variable if not already done by user
  set_fact:
    elasticsearch_ca: "{{ groups['elasticsearch'][0] }}"
  when: elasticsearch_http_security | bool and elasticsearch_ca is undefined
  tags:
    - certificates

- name: Create directory for logging if file logging is activated
  file:
    path: "{{ beats_logpath }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  when: beats_logging == "file"

- import_tasks: beats-security.yml
  when: elasticsearch_http_security | bool

- import_tasks: filebeat.yml
  when: beats_filebeat | bool

- import_tasks: metricbeat.yml
  when: beats_metricbeat | bool
