---

- name: Enable security if enabled for whole stack
  set_fact:
    beats_security: true
  when:
    - elastic_stack_full_stack | bool
    - elastic_security | bool

- name: Set elasticsearch_ca variable if not already done by user
  set_fact:
    elasticsearch_ca: "{{ groups['elasticsearch'][0] }}"
  when:
    - beats_security | bool
    - elasticsearch_ca is undefined
  tags:
    - certificates

- name: Create directory for logging if file logging is activated
  file:
    path: "{{ beats_logpath }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  when: beats_logging == "file"

- import_tasks: beats-security.yml
  when:
    - beats_security | bool
    - elastic_stack_full_stack | bool
    - elastic_variant == "elastic"

- import_tasks: filebeat.yml
  when: beats_filebeat | bool

- import_tasks: auditbeat.yml
  when: beats_auditbeat | bool

- import_tasks: metricbeat.yml
  when: beats_metricbeat | bool
