---
- name: Ensure Elastic repository key is available (RedHat)
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
- name: Ensure Elasticsearch yum repository is configured (RedHat)
  yum_repository:
    name: elastic-{{ elastic_release }}.x
    description: Elastic Release {{ elastic_release }}.x
    file: elastic-release
    baseurl: https://artifacts.elastic.co/packages/{{ elastic_release }}.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
