---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
#
# Currently security is not implemented with OSS. We leave the variable set
# to check for handling of misconfiguration (and be prepared for upcoming
# implementations)
# But we need to deactivate security in Elasticsearch to not lock out
# Logstash
- name: Converge
  hosts: all
  collections:
    - netways.elasticstack
  vars:
    elasticstack_full_stack: true
    elasticstack_variant: oss
    logstash_security: false
    elasticstack_security: false
    beats_filebeat_syslog_udp: true
    beats_filebeat_syslog_tcp: true
    logstash_beats_tls: false
    elasticstack_release: 7
  tasks:
    - name: "Include Elastics repos role"
      ansible.builtin.include_role:
        name: repos
    - name: Install rsyslog
      ansible.builtin.package:
        name: rsyslog
    - name: Start rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: started
    - name: "Include Elasticsearch role"
      ansible.builtin.include_role:
        name: elasticsearch
    - name: "Include Beats"
      ansible.builtin.include_role:
        name: beats
    - name: "Include Redis"
      ansible.builtin.include_role:
        name: geerlingguy.redis
    - name: "Include Logstash"
      ansible.builtin.include_role:
        name: logstash
    - name: Configure rsyslog
      ansible.builtin.lineinfile:
        line: "*.* @@localhost:514"
        path: /etc/rsyslog.conf
    - name: Restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted
      changed_when: false
