---
# This is an example playbook to execute Ansible tests.

- name: Check if Logstash configuration does what it should
  hosts: all
  vars:
    elasticstack_elasticsearch_http_port: 9200
    elasticstack_beats_port: 5044
  tasks:
  - name: Give some time for tools to connect
    wait_for:
      timeout: 120
  - name: Run syntax check
    command: "/usr/share/logstash/bin/logstash --path.settings=/etc/logstash -t"
    when: "'logstash' in group_names"
  - name: Check for open port tcp {{ elasticstack_beats_port }}
    wait_for:
      port: "{{ elasticstack_beats_port }}"
    when: "'logstash' in group_names"
  - name: Query for Logstasch indices
    shell: >
      curl -s http://localhost:{{ elasticstack_elasticsearch_http_port }}/_cat/indices |
      grep logstash |
      awk {' print $7 '} |
      sort -n |
      tail -1
    register: logstash_count
    when: "'elasticsearch' in group_names"
  - name: Show full output
    debug:
      var: logstash_count
    when: "'elasticsearch' in group_names"
  - name: Fail when logstash is empty
    fail:
      msg: "Logstash Index is empty"
    when: "'elasticsearch' in group_names and logstash_count.stdout == 0"
  - name: Show number of received events
    debug:
      msg: "Elasticsearch received {{ logstash_count.stdout }} events so far"
    when: "'elasticsearch' in group_names"
