---
# The workaround for arbitrarily named role directory is important because the git repo has one name and the role within it another
# Found at: https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  collections:
    - NETWAYS.elasticstack
  vars:
    elastic_variant: oss
    elastic_rpm_workaround: true
    elastic_release: "{{ lookup('env', 'ELASTIC_RELEASE') | int}}"
  tasks:
    - name: "Include Elastic Repos"
      ansible.builtin.include_role:
        name: repos
