---
# The workaround for arbitrarily named role directory is important because the git repo has one name and the role within it another
# Found at: https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  collections:
    - netways.elasticstack
  vars:
    elasticstack_variant: oss
    elasticstack_rpm_workaround: true
    elasticstack_release: 7
    elasticstack_no_log: false
  tasks:
    - name: "Include Elastic Repos"
      ansible.builtin.include_role:
        name: repos
