---
# handlers file for beats
#
- name: Restart Filebeat
  service:
    name: filebeat
    state: restarted
  when:
    - beats_filebeat | bool
    - filebeat_enable | bool

- name: Restart Auditbeat
  service:
    name: auditbeat
    state: restarted
  when:
    - beats_auditbeat | bool
    - auditbeat_enable | bool

- name: Restart Metricbeat
  service:
    name: metricbeat
    state: restarted
  when:
  - beats_metricbeat | bool
  - metricbeat_enable | bool
