---
# handlers file for beats
#
- name: Restart Filebeat
  service:
    name: filebeat
    state: restarted
  when:
    - beats_filebeat | bool
    - beats_filebeat_enable | bool

- name: Restart Auditbeat
  service:
    name: auditbeat
    state: restarted
  when:
    - beats_auditbeat | bool
    - beats_auditbeat_enable | bool

- name: Restart Metricbeat
  service:
    name: metricbeat
    state: restarted
  when:
    - beats_metricbeat | bool
    - beats_metricbeat_enable | bool
