---
# handlers file for elasticsearch
- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
  when: elasticsearch_enable | bool

- name: Restart kibana if available for elasticsearch certificates
  include_tasks: handlers/restart_kibana.yml
  with_items: "{{ groups['kibana'] }}"
  when:
    - elastic_stack_full_stack: true
    - "not 'renew_ca' in ansible_run_tags"
    - "not elastic_ca_will_expire_soon | bool"
