---
# handlers file for elasticsearch
- name: Restart Elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    state: restarted
    daemon_reload: yes
  when:
    - elasticsearch_enable | bool
    - not elasticsearch_freshstart.changed | bool
    - not elasticsearch_freshstart_security.changed | bool

- name: Restart kibana if available for elasticsearch certificates
  ansible.builtin.include_tasks: handlers/restart_kibana.yml
  with_items: "{{ groups[elasticstack_kibana_group_name] }}"
  when:
    - elasticstack_collection_managed: true
    - "not 'renew_ca' in ansible_run_tags"
    - "not elasticstack_ca_will_expire_soon | bool"
    - elasticstack_kibana_group_name is defined
    - groups[elasticstack_kibana_group_name] is defined
