---
- name: Restart Elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    state: restarted
    daemon_reload: yes
  when:
    - elasticsearch_enable | bool
    - not elasticsearch_freshstart.changed | bool
    - not elasticsearch_freshstart_security.changed | bool
