---
- name: Check if kibana is installed
  ansible.builtin.package_facts:
    manager: "auto"
  changed_when: false

- name: Restart Kibana
  ansible.builtin.service:
    name: kibana
    state: restarted
  delegate_to: "{{ item }}"
  when: "'kibana' in ansible_facts.packages"
