---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role
# within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  vars:
    logstash_enable: true
    logstash_plugins:
      - logstash-filter-cidr
      - logstash-output-icinga
    logstash_global_ecs: "v1"
    logstash_pipelines:
      syslog:
        name: syslog
        source: https://github.com/widhalmt/syslog-logstash-pipeline.git
        input: syslog
        output: syslog
    logstash_connector_pipelines:
      - name: forwarder-distribute
        exclusive: false
        input:
          - name: syslog
            key: netways-syslog-output
        output:
          - name: forwarder
            key: forwarder
  tasks:
    - name: "Include Elastics repos role"
      include_role:
        name: elastic-repos
    - name: "Include Redis"
      include_role:
        name: geerlingguy.redis
    - name: "Include Logstash"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
