---
- name: Prepare
  hosts: all
  tasks:
    - name: Install git
      package:
        name: git
    - name: Install packages for Debian
      package:
        name:
          - gpg
          - procps
          - curl
      when: ansible_os_family == "Debian"
