---
- name: Prepare
  hosts: all
  tasks:
    - name: Install packages needed for Debian
      apt:
        name:
          - gpg
          - curl
          - procps
          - gpg-agent
          - openssl
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install common packages
      package:
        name:
          - git
          - openssl
