---
- name: Prepare
  hosts: all
  tasks:
    - name: Refresh apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Install git
      package:
        name: git
    - name: Install packages for Debian
      package:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
      when: ansible_os_family == "Debian"
    - name: Install unzip for certificate handling
      package:
        name: unzip
