---
# The workaround for arbitrarily named role directory is important because the git repo has one name and the role within it another
# Found at: https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  collections:
    - netways.elasticstack
  hosts: all
  vars:
    elasticsearch_security: false
    elasticstack_security: false
    elasticsearch_jna_workaround: true
    elasticsearch_disable_systemcallfilterchecks: true
    elasticsearch_heap: "1"
    elasticstack_release: 7
    elasticstack_no_log: false
    elasticstack_elasticsearch_group_name: elasticsearchXYZ
  tasks:
    - name: Include Elastics repos role
      ansible.builtin.include_role:
        name: repos
    - name: Include Elasticsearch
      ansible.builtin.include_role:
        name: elasticsearch
