---
- name: Prepare
  hosts: all
  tasks:
    - name: Install packages for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
          - git
        update_cache: yes
      when: ansible_os_family == "Debian"
