---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    elastic_initial_passwords: /usr/share/elasticsearch/initial_passwords
  tasks:

# Remember, this is the no-security scenario. So no https
  - name: Health check
    uri:
      url: http://localhost:9200/_cluster/health
      method: GET
      force_basic_auth: yes
      user: elastic
      password: "{{ elastic_password.stdout }}"
      return_content: yes
      status_code: 200
      validate_certs: false
    register: result
    until: result.json.status == "green"
    retries: 6
    delay: 10

  - name: Node check
    uri:
      url: http://localhost:9200/_cat/nodes
      method: GET
      force_basic_auth: yes
      user: elastic
      password: "{{ elastic_password.stdout }}"
      return_content: yes
      status_code: 200
      validate_certs: false
    register: nodes
