---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    elasticstack_elasticsearch_http_port: 9200
    elasticstack_elasticsearch_group_name: elasticsearch
  tasks:

# Remember, this is the no-security scenario. So no https
    - name: Health check
      ansible.builtin.uri:
        url: http://localhost:{{ elasticstack_elasticsearch_http_port }}/_cluster/health
        method: GET
        return_content: yes
        status_code: 200
        validate_certs: false
      register: result
      until: result.json.status == "green"
      retries: 6
      delay: 10
      when: groups[elasticstack_elasticsearch_group_name] | length > 1

    - name: Node check
      ansible.builtin.uri:
        url: http://localhost:{{ elasticstack_elasticsearch_http_port }}/_cat/nodes
        method: GET
        return_content: yes
        status_code: 200
        validate_certs: false
      register: nodes
      when: groups[elasticstack_elasticsearch_group_name] | length > 1

    - name: Check if all Nodes see each other
      ansible.builtin.assert:
        that:
          - "'{{ item }}' in nodes.content"
        fail_msg: "'{{ item }}' was not found in nodes.content"
        success_msg: "'{{ item }}' was found in nodes.content"
      with_inventory_hostnames: all
      when: groups[elasticstack_elasticsearch_group_name] | length > 1
