---

- name: Check if TLS certificate exists
  ansible.builtin.stat:
    path: "{{ kibana_tls_cert }}"
  register: cert_stat

- name: Check if TLS key exists
  ansible.builtin.stat:
    path: "{{ kibana_tls_key }}"
  register: key_stat

- name: Generate default OpenSSL Kibana TLS key
  ansible.builtin.command:
    cmd: openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out {{ kibana_tls_key }}
  when: not key_stat.stat.exists
  changed_when: not key_stat.stat.exists

- name: Generate default OpenSSL Kibana TLS certificate
  ansible.builtin.command:
    cmd: openssl req -x509 -key {{ kibana_tls_key }} -out {{ kibana_tls_cert }} -days 3650 -nodes -subj "/CN={{ ansible_fqdn }}"
  when: not cert_stat.stat.exists
  changed_when: not cert_stat.stat.exists

- name: Set proper permissions for Kibana TLS certificate
  ansible.builtin.file:
    path: "{{ kibana_tls_cert }}"
    mode: '0644'
    owner: kibana
    group: kibana

- name: Set proper permissions for Kibana TLS key
  ansible.builtin.file:
    path: "{{ kibana_tls_key }}"
    mode: '0600'
    owner: kibana
    group: kibana
