---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    elastic_initial_passwords: /usr/share/elasticsearch/initial_passwords
  tasks:

  - name: Set elasticsearch_ca variable if not already done by user
    set_fact:
      elasticsearch_ca: "{{ groups['elasticsearch'][0] }}"
    when: elasticsearch_ca is undefined

  - name: Fetch Elastic password
    shell: grep "PASSWORD elastic" {{ elastic_initial_passwords }} | awk {' print $4 '}
    register: elastic_password
    changed_when: false
    delegate_to: "{{ elasticsearch_ca }}"


# Remember, this is the no-security scenario. So no https
  - name: Health check
    uri:
      url: http://localhost:9200/_cluster/health
      method: GET
      force_basic_auth: yes
      user: elastic
      password: "{{ elastic_password.stdout }}"
      return_content: yes
      status_code: 200
      validate_certs: false
    register: result
    until: result.json.status == "green"
    retries: 6
    delay: 10

  - name: Node check
    uri:
      url: http://localhost:9200/_cat/nodes
      method: GET
      force_basic_auth: yes
      user: elastic
      password: "{{ elastic_password.stdout }}"
      return_content: yes
      status_code: 200
      validate_certs: false
    register: nodes
