name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["needs-triage"]
type: ["bug"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Please try to fill out as much of the information below as you can. Thank you!
      options:
        - label: Yes, I've searched similar issues on GitHub and didn't find any.
          required: true
  - type: input
    id: app_version
    attributes:
      label: Which version contains the bug?
      placeholder: 1.0.0
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Describe how to reproduce the bug.
  - type: textarea
    id: environment
    attributes:
      label: Your Environment
      description: Include as many relevant details about the environment you experienced the problem in.
      value: |
        * Version (commit) used:
        * Ansible version:
        * Python version:
        * Operating System and version:
