---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  collections:
    - netways.elasticstack
  vars:
    elasticstack_full_stack: true
    beats_filebeat_syslog_udp: true
    beats_filebeat_syslog_tcp: true
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | int}}"
  tasks:
    - name: Include repos role
      include_role:
        name: repos
    - name: Install rsyslog
      package:
        name: rsyslog
    - name: Start rsyslog
      service:
        name: rsyslog
        state: started
    - name: Include Elasticsearch role
      include_role:
        name: elasticsearch
    - name: Include Beats
      include_role:
        name: beats
    - name: Include Redis
      include_role:
        name: geerlingguy.redis
    - name: Include Logstash
      include_role:
        name: logstash
    - name: Configure rsyslog
      lineinfile:
        line: "*.* @@localhost:514"
        path: /etc/rsyslog.conf
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
      changed_when: false
