---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kibana-full
    groups:
      - elasticsearch
      - kibana
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
