---
name: Molecule Test
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install yamllint ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'

  molecule_default:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        distro: [ubuntu2204]
        scenario: [default]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-test.txt

      - name: Test with molecule
        run: |
          molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  molecule_tests:
    runs-on: ubuntu-latest
    needs: molecule_default

    strategy:
      max-parallel: 1
      matrix:
        distro: [ubuntu2204]
        scenario: [run_logstash,
                   full_stack,
                   full_stack-oss,
                   specific_version,
                   pipelines]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-test.txt

      - name: Test with molecule
        run: |
          molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
