---
- name: Converge
  collections:
    - netways.elasticstack
  hosts: all
  vars:
    elasticsearch_jna_workaround: true
    elasticsearch_disable_systemcallfilterchecks: true
    elastic_release: "{{ lookup('env', 'ELASTIC_RELEASE') | int}}"
    elasticsearch_heap: "1"
  tasks:
    - name: Include Elastic Repos
      include_role:
        name: repos
    - name: Include Elasticsearch role
      include_role:
        name: elasticsearch
    - name: Include logstash
      include_role:
        name: logstash
    - name: Include Kibana
      include_role:
        name: kibana
    - name: Include Beats
      include_role:
        name: beats
