---

# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722

- name: Converge
  collections:
    - netways.elasticstack
  hosts: all
  vars:
    elasticsearch_jna_workaround: true
    elasticsearch_disable_systemcallfilterchecks: true
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | int}}"
    elasticsearch_heap: "2"
    elasticstack_full_stack: true
    logstash_pipeline_unsafe_shutdown: true
    beats_filebeat_syslog_udp: true
    beats_filebeat_syslog_tcp: true
    beats_filebeat_modules:
      - system
    beats_fields:
      - "testbed: molecule"
  tasks:
    - name: Enable Elastic installation on RHEL 9
      ansible.builtin.set_fact:
        elasticstack_rpm_workaround: true
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version >= "9"
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Install dependencies
      package:
        name:
          - curl
    - name: Include Redis
      ansible.builtin.include_role:
        name: geerlingguy.redis
    - name: Include Elastic Repos
      ansible.builtin.include_role:
        name: repos
    - name: Include Elasticsearch role
      ansible.builtin.include_role:
        name: elasticsearch
    - name: Include logstash
      ansible.builtin.include_role:
        name: logstash
    - name: Include Beats
      ansible.builtin.include_role:
        name: beats
    - name: Install rsyslog
      ansible.builtin.package:
        name: rsyslog
    - name: Configure rsyslog
      ansible.builtin.lineinfile:
        line: "*.* @@localhost:514"
        path: /etc/rsyslog.conf
    - name: Start rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: started
    - name: Include kibana
      ansible.builtin.include_role:
        name: kibana
    - name: Include Beats
      ansible.builtin.include_role:
        name: beats
