---

# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722

- name: Converge
  collections:
    - netways.elasticstack
  hosts: all
  vars:
    elasticsearch_jna_workaround: true
    elasticsearch_disable_systemcallfilterchecks: true
    elasticsearch_monitoring_enabled: false
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | int}}"
    elasticsearch_heap: "2"
    elasticstack_collection_managed: true
    elasticstack_no_log: false
    logstash_pipeline_unsafe_shutdown: true
    logstash_redis_password: "{{ lookup('ansible.builtin.password', '/tmp/redispassword', chars=['ascii_letters'], length=15) }}"
    redis_requirepass: "{{ logstash_redis_password }}"
    beats_filebeat_journald: true
    beats_filebeat_modules:
      - system
    beats_fields:
      - "testbed: molecule"
    kibana_extra_config: |-
      ops.interval: 5000
  tasks:
    - name: Include Redis
      ansible.builtin.include_role:
        name: geerlingguy.redis
    - name: Include Elastic Repos
      ansible.builtin.include_role:
        name: repos
    - name: Include Elasticsearch role
      ansible.builtin.include_role:
        name: elasticsearch
    - name: Include logstash
      ansible.builtin.include_role:
        name: logstash
    - name: Include kibana
      ansible.builtin.include_role:
        name: kibana
    - name: Include Beats
      ansible.builtin.include_role:
        name: beats
