---
- name: Prepare
  hosts: all
  tasks:
    - name: Install packages for RHEL
      package:
        name:
          - iproute
          - NetworkManager
      when: ansible_os_family == "RedHat"

    - name: Start NetworkManager
      service:
        name: NetworkManager
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Install packages for Debian
      apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install common packages
      package:
        name:
          - git
          - openssl
          - unzip
          - systemd
    
    - name: Update all installed packages RHEL
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      when: ansible_os_family == "RedHat"

    - name: Update all installed packages Debian
      apt:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"
