---
galaxy_info:
  role_name: elasticsearch
  author: Netways GmbH
  description: Elasticsearch Ansible role
  company: Netways GmbH
  namespace: netways
  license: GPL-3.0-or-later
  min_ansible_version: "2.19" # Lower version may work
  platforms:
    - name: EL
      versions:
        - "9"
    - name: Ubuntu
      versions:
        - "22.04"
  galaxy_tags:
    - elasticsearch
    - elk
    - search
    - database
    - logging
    - analytics
    - elastic

collections:
  - netways.elasticstack
