---
- name: Converge
  hosts: all
  collections:
    - netways.elasticstack
  vars:
    elasticstack_rpm_workaround: true
    elasticstack_full_stack: false
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | int}}"
  tasks:
    - name: Include Elastic Repos
      ansible.builtin.include_role:
        name: repos
