---
- name: Prepare
  hosts: all
  tasks:
    - name: Install requirements for Debian
      ansible.builtin.apt:
        name:
        - gpg
        - apt-transport-https
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Install requirements for Ubuntu
      ansible.builtin.apt:
        name:
        - gpg-agent
        update_cache: yes
      when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"
