---
# defaults file for kibana
kibana_enable: true
kibana_config_backup: true
kibana_manage_yaml: true

kibana_security: true
kibana_tls: false
kibana_tls_cert: /etc/kibana/certs/cert.pem
kibana_tls_key: /etc/kibana/certs/key.pem
kibana_tls_key_passphrase: PleaseChangeMe
kibana_cert_expiration_buffer: 30
kibana_cert_validity_period: 1095
kibana_cert_will_expire_soon: false
kibana_sniff_on_start: false
kibana_sniff_on_connection_fault: false
kibana_custom_default_index: 979390d0-3def-11ea-ad1f-5b09c073c7d3

kibana_manage_logging: false
kibana_logpath: /var/log/kibana
kibana_logfile: kibana.log
kibana_loglevel: info
kibana_logging_layout: pattern
kibana_logging_console: true
kibana_logging_rotate_policy: size-limit
kibana_logging_rotate_size: 100mb
kibana_logging_rotate_interval: 24h
kibana_logging_rotate_keep: 10

kibana_freshstart:
  changed: false
