---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    elasticstack_initial_passwords: /usr/share/elasticsearch/initial_passwords
    elasticstack_elasticsearch_http_port: 9200
  tasks:

    - name: Set elasticstack_ca variable if not already done by user
      set_fact:
        elasticstack_ca: "{{ groups['elasticsearch'][0] }}"
      when: elasticstack_ca is undefined

    - name: Fetch Elastic password
      shell: grep "PASSWORD elastic" {{ elasticstack_initial_passwords }} | awk {' print $4 '}
      register: elasticstack_password
      changed_when: false
      delegate_to: "{{ elasticstack_ca }}"

    - name: Health check
      uri:
        url: https://localhost:{{ elasticstack_elasticsearch_http_port }}/_cluster/health
        method: GET
        force_basic_auth: yes
        user: elastic
        password: "{{ elasticstack_password.stdout }}"
        return_content: yes
        status_code: 200
        validate_certs: false
      register: result
      until: result.json.status == "green"
      retries: 6
      delay: 10

    - name: Node check
      uri:
        url: https://localhost:{{ elasticstack_elasticsearch_http_port }}/_cat/nodes
        method: GET
        force_basic_auth: yes
        user: elastic
        password: "{{ elasticstack_password.stdout }}"
        return_content: yes
        status_code: 200
        validate_certs: false
      register: nodes

    - name: Check if all Nodes see each other
      ansible.builtin.assert:
        that:
          - "'{{ item }}' in nodes.content"
        fail_msg: "'{{ item }}' was not found in nodes.content"
        success_msg: "'{{ item }}' was found in nodes.content"
      with_inventory_hostnames: all
