---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    elastic_initial_passwords: /usr/share/elasticsearch/initial_passwords
  tasks:

  - name: Set elasticsearch_ca variable if not already done by user
    set_fact:
      elasticsearch_ca: "{{ groups['elasticsearch'][0] }}"
    when: elasticsearch_ca is undefined

  - name: Fetch Elastic password
    shell: grep "PASSWORD elastic" {{ elastic_initial_passwords }} | awk {' print $4 '}
    register: elastic_password
    changed_when: false
    delegate_to: "{{ elasticsearch_ca }}"

  - name: Health check
    uri:
      url: https://localhost:9200/_cluster/health
      method: GET
      force_basic_auth: yes
      user: elastic
      password: "{{ elastic_password.stdout }}"
      return_content: yes
      status_code: 200
      validate_certs: false
    register: result
    until: result.json.status == "green"
    retries: 6
    delay: 10

  - name: Node check
    uri:
      url: https://localhost:9200/_cat/nodes
      method: GET
      force_basic_auth: yes
      user: elastic
      password: "{{ elastic_password.stdout }}"
      return_content: yes
      status_code: 200
      validate_certs: false
    register: nodes

  - name: Check if all Nodes see each other
    ansible.builtin.assert:
      that:
        - "'{{ item }}' in nodes.content"
      fail_msg: "'{{ item }}' was not found in nodes.content"
      success_msg: "'{{ item }}' was found in nodes.content"
    with_inventory_hostnames: all
