galaxy_info:
  role_name: kibana
  author: netways
  description: Ansible role for Kibana
  company: Netways GmbH
  license: GPL-3.0-or-later

  min_ansible_version: "2.4"
  platforms:
  - name: CentOS
    versions:
    - 7
  - name: Debian
    versions:
    - 10

  galaxy_tags: []
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
