---
- name: Bootstrap Python 3.9 on Rocky Linux 8
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 3.9 if not yet available (Rocky Linux 8)
      ansible.builtin.raw: |
        grep -qs "Rocky Linux release 8" /etc/redhat-release && dnf install -y python39 || true
      changed_when: false

- name: Prepare
  hosts: all
  tasks:
    - name: Refresh apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install git
      ansible.builtin.package:
        name: git

    - name: Install packages for RHEL
      ansible.builtin.package:
        name:
          - iproute
          - NetworkManager
      when: ansible_os_family == "RedHat"

    - name: Start NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Install packages for Debian
      ansible.builtin.package:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
      when: ansible_os_family == "Debian"
