---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  vars:
    filebeat_log_inputs:
      messages:
        name: messages
        paths:
          - /var/log/messages
        multiline:
          type: pattern
          pattern: '^[[:space:]]+(at|\.{3})[[:space:]]+\b|^Caused by:'
          negate: false
          match: after
    filebeat_mysql_slowlog_input: true
    beats_metricbeat: true
    metricbeat_output: logstash
  tasks:
    - name: "Include Elastics repos role"
      include_role:
        name: elastic-repos
    - name: "Include Beats"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
