---
# handlers file for kibana
- name: Restart Kibana
  service:
    name: kibana
    state: restarted

- name: Restart Elasticsearch for Kibana certificates
  service:
    state: restarted
    name: elasticsearch
  with_items: "{{ groups['elasticsearch'] }}"
  delegate_to: "{{ item }}"
  when:
    - elastic_stack_full_stack: true
