---

- name: elasticsearch_bootstrap_pw genpw
  shell:
    cmd: cat /proc/sys/kernel/random/uuid | sed 's/[-]//g' | head -c 20; echo;
    register: register_elasticsearch_bootstrap_pw
  when: elasticsearch_bootstrap_pw is undefined


- set_fact:
    elasticsearch_bootstrap_pw = {{ register_elasticsearch_bootstrap_pw.stdout }}
  when: register_elasticsearch_bootstrap_pw is defined

