# Ansible
#
# Rolling Upgrade of Elasticsearch with security on
# Source from: author: Jeff Steinmetz, @jeffsteinmetz; Bin Li, @holysoros
# Modifications: author: Daniel Neuberger @netways.de
# More modifications: NETWAYS Professional Services GmbH
# latest tested with Ansible 2.9 and later

---

# For now we support upgrade only for clusters with security enabled
# If you positively need support for safely upgrading clusters without security,
# feel free to open an issue at https://github.com/NETWAYS/ansible-collection-elasticstack/issues

- name: Start elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    enabled: yes
    state: started
  when:
    - elasticsearch_running.status.ActiveState == "active"
    - not elasticsearch_unsafe_upgrade_restart | bool

- name: Restart elasticsearch (fast, for non-prod)
  ansible.builtin.service:
    name: elasticsearch
    enabled: yes
    state: restarted
  when:
    - elasticsearch_running.status.ActiveState == "active"
    - elasticsearch_unsafe_upgrade_restart | bool

- name: Wait for elasticsearch node to come back up if it was stopped
  ansible.builtin.wait_for:
    host: "{{ elasticsearch_api_host }}"
    port: "{{ elasticstack_elasticsearch_http_port }}"
    delay: 30

- name: Confirm the node joins the cluster # noqa: risky-shell-pipe
  ansible.builtin.shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    curl
    -k
    -u elastic:{{ elasticstack_password.stdout }}
    -s
    -m 2
    '{{ elasticsearch_http_protocol }}://{{ elasticsearch_api_host }}:{{ elasticstack_elasticsearch_http_port }}/_cat/nodes?h=name'
    | grep
    -E
    '^{{ elasticsearch_nodename }}$'
  register: result
  until: result.rc == 0
  retries: 200
  delay: 3
  changed_when: false

- name: Enable shard allocation for the cluster
  ansible.builtin.uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_api_host }}:{{ elasticstack_elasticsearch_http_port }}/_cluster/settings"
    method: PUT
    body: '{ "persistent": { "cluster.routing.allocation.enable": null }}'
    body_format: json
    user: elastic
    password: "{{ elasticstack_password.stdout }}"
    validate_certs: no
  register: response
  # next line is boolean not string, so no quotes around true
  # use python truthiness
  until: "response.json.acknowledged == true"
  retries: 5
  delay: 30

- name: Wait for cluster health to return to yellow or green
  ansible.builtin.uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_api_host }}:{{ elasticstack_elasticsearch_http_port }}/_cluster/health"
    method: GET
    user: elastic
    password: "{{ elasticstack_password.stdout }}"
    validate_certs: no
  register: response
  until: "response.json.status == 'yellow' or response.json.status == 'green'"
  retries: 5
  delay: 30
