---

- name: Create keystore
  command: /usr/share/elasticsearch/bin/elasticsearch-keystore create
  args:
    creates: /etc/elasticsearch/elasticsearch.keystore

- name: Check for bootstrap password
  command: /usr/share/elasticsearch/bin/elasticsearch-keystore list
  changed_when: false
  register: elasticsearch_keystore

- name: Set bootstrap password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    echo "{{ elasticsearch_bootstrap_pw }}" |
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    add -x 'bootstrap.password'
  when: "'bootstrap.password' not in elasticsearch_keystore.stdout_lines"
  changed_when: false
  no_log: true
  notify:
    - Restart Elasticsearch
  ignore_errors: "{{ ansible_check_mode }}"

- name: Get xpack.security.http.ssl.keystore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    show 'xpack.security.http.ssl.keystore.secure_password'
  when:
    - "'xpack.security.http.ssl.keystore.secure_password' in elasticsearch_keystore.stdout_lines"
    - elasticsearch_http_security
  register: elasticsearch_http_ssl_keystore_secure_password
  ignore_errors: "{{ ansible_check_mode }}"
  no_log: true
  changed_when: false

- name: Set xpack.security.http.ssl.keystore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    echo "{{ elasticsearch_tls_key_passphrase }}" |
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    add -f -x 'xpack.security.http.ssl.keystore.secure_password'
  changed_when: false
  no_log: true
  when:
    - elasticsearch_http_ssl_keystore_secure_password.stdout is undefined or elasticsearch_tls_key_passphrase != elasticsearch_http_ssl_keystore_secure_password.stdout
    - elasticsearch_http_security
  notify:
    - Restart Elasticsearch

- name: Remove xpack.security.http.ssl.keystore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    remove 'xpack.security.http.ssl.keystore.secure_password'
  changed_when: false
  no_log: true
  when:
    - "'xpack.security.http.ssl.keystore.secure_password' in elasticsearch_keystore.stdout_lines"
    - not elasticsearch_http_security
  notify:
    - Restart Elasticsearch

- name: Get xpack.security.http.ssl.truststore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    show 'xpack.security.http.ssl.truststore.secure_password'
  when:
    - "'xpack.security.http.ssl.truststore.secure_password' in elasticsearch_keystore.stdout_lines"
    - elasticsearch_http_security
  register: elasticsearch_http_ssl_truststore_secure_password
  ignore_errors: "{{ ansible_check_mode }}"
  no_log: true
  changed_when: false

- name: Set xpack.security.http.ssl.truststore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    echo "{{ elasticsearch_tls_key_passphrase }}" |
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    add -f -x 'xpack.security.http.ssl.truststore.secure_password'
  changed_when: false
  no_log: true
  when:
    - elasticsearch_http_ssl_truststore_secure_password.stdout is undefined or elasticsearch_tls_key_passphrase != elasticsearch_http_ssl_truststore_secure_password.stdout
    - elasticsearch_http_security
  notify:
    - Restart Elasticsearch

- name: Remove xpack.security.http.ssl.truststore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    remove 'xpack.security.http.ssl.truststore.secure_password'
  changed_when: false
  no_log: true
  when:
    - "'xpack.security.http.ssl.truststore.secure_password' in elasticsearch_keystore.stdout_lines"
    - not elasticsearch_http_security
  notify:
    - Restart Elasticsearch

- name: Get xpack.security.transport.ssl.keystore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    show 'xpack.security.transport.ssl.keystore.secure_password'
  when:
    - "'xpack.security.transport.ssl.keystore.secure_password' in elasticsearch_keystore.stdout_lines"
    - elasticsearch_security
  register: elasticsearch_transport_ssl_keystore_secure_password
  ignore_errors: "{{ ansible_check_mode }}"
  no_log: true
  changed_when: false

- name: Set xpack.security.transport.ssl.keystore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    echo "{{ elasticsearch_tls_key_passphrase }}" |
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    add -f -x 'xpack.security.transport.ssl.keystore.secure_password'
  changed_when: false
  no_log: true
  when:
    - elasticsearch_transport_ssl_keystore_secure_password.stdout is undefined or elasticsearch_tls_key_passphrase != elasticsearch_transport_ssl_keystore_secure_password.stdout
    - elasticsearch_security
  notify:
    - Restart Elasticsearch

- name: Remove xpack.security.transport.ssl.keystore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    remove 'xpack.security.transport.ssl.keystore.secure_password'
  changed_when: false
  no_log: true
  when:
    - "'xpack.security.transport.ssl.keystore.secure_password' in elasticsearch_keystore.stdout_lines"
    - not elasticsearch_security
  notify:
    - Restart Elasticsearch

- name: Get xpack.security.transport.ssl.truststore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    show 'xpack.security.transport.ssl.truststore.secure_password'
  when:
    - "'xpack.security.transport.ssl.truststore.secure_password' in elasticsearch_keystore.stdout_lines"
    - elasticsearch_security
  register: elasticsearch_transport_ssl_truststore_secure_password
  ignore_errors: "{{ ansible_check_mode }}"
  no_log: true
  changed_when: false

- name: Set xpack.security.transport.ssl.truststore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    echo "{{ elasticsearch_tls_key_passphrase }}" |
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    add -f -x 'xpack.security.transport.ssl.truststore.secure_password'
  changed_when: false
  no_log: true
  when:
    - elasticsearch_transport_ssl_truststore_secure_password.stdout is undefined or elasticsearch_tls_key_passphrase != elasticsearch_transport_ssl_truststore_secure_password.stdout
    - elasticsearch_security
  notify:
    - Restart Elasticsearch

- name: Remove xpack.security.transport.ssl.truststore.secure_password # noqa: risky-shell-pipe
  shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    /usr/share/elasticsearch/bin/elasticsearch-keystore
    remove 'xpack.security.transport.ssl.truststore.secure_password'
  changed_when: false
  no_log: true
  when:
    - "'xpack.security.transport.ssl.truststore.secure_password' in elasticsearch_keystore.stdout_lines"
    - not elasticsearch_security
  notify:
    - Restart Elasticsearch
