---

- name: Check for Elasticsearch package (RedHat) # noqa: risky-shell-pipe
  ansible.builtin.shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    rpm -q elasticsearch |
    cut -d- -f2
  register: elasticsearch_version_output
  failed_when: false
  changed_when: false
  when:
    - ansible_os_family == "RedHat"

- name: Check for Elasticsearch package (Debian) # noqa: risky-shell-pipe
  ansible.builtin.shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    dpkg -s elasticsearch |
    grep Version |
    cut -d: -f2 |
    cut -d- -f1 |
    tr -d [:space:]
  register: elasticsearch_version_output
  failed_when: false
  changed_when: false
  when:
    - ansible_os_family == "Debian"

- name: Set friendly name of version variable
  ansible.builtin.set_fact:
    elasticsearch_current_version: "{{ elasticsearch_version_output.stdout }}"
  when:
    - elasticsearch_version_output.stdout is defined
