# Ansible
#
# Rolling Upgrade of Elasticsearch with security on
# Source from: author: Jeff Steinmetz, @jeffsteinmetz; Bin Li, @holysoros
# Modifications: author: Daniel Neuberger @netways.de
# More modifications: NETWAYS Professional Services GmbH
# latest tested with Ansible 2.9 and later

---

# For now we support upgrade only for clusters with security enabled
# If you positively need support for safely upgrading clusters without security,
# feel free to open an issue at https://github.com/NETWAYS/ansible-collection-elasticstack/issues
- name: Set connection protocol to https
  ansible.builtin.set_fact:
    elasticsearch_http_protocol: "https"

# This step is here primarily in order to recover from broken/restarted upgrade or rolling restart.
# TODO: Only run this task for the first host.
- name: Cluster health check
  ansible.builtin.include_tasks: elasticsearch-wait-for-cluster-health.yml


# Disabling shard allocation right after enabling it seems redundant. Please see above for details.
- name: Disable shard allocation for the cluster
  ansible.builtin.uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_api_host }}:{{ elasticstack_elasticsearch_http_port }}/_cluster/settings"
    method: PUT
    body: '{ "persistent": { "cluster.routing.allocation.enable": "none" }}'
    body_format: json
    user: elastic
    password: "{{ elasticstack_password.stdout }}"
    validate_certs: no

- name: Stop non essential indexing to speed up shard recovery
  ansible.builtin.uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_api_host }}:{{ elasticstack_elasticsearch_http_port }}/_flush"
    method: POST
    user: elastic
    password: "{{ elasticstack_password.stdout }}"
    validate_certs: no
  failed_when: false

- name: Shutdown elasticsearch service
  ansible.builtin.service:
    name: elasticsearch
    enabled: yes
    state: stopped
  when:
    - not elasticsearch_unsafe_upgrade_restart | bool
