---
# Work in progress, do not use!

# Collective work by Thomas Widhalm & Patrick Dolinic

#- name: Password Generation - Check if the Password File exists
#  stat:
#    path: /usr/share/elasticsearch/generated_passwords
#  register: stat_password
#
##- debug: var=stat_password
#
#- name: Grep for Password in File
#  shell:
#    cmd: 'grep "elasticsearch_bootstrap_pw" /usr/share/elasticsearch/generated_passwords | cut -d: -f2'
#  register: pw_generated_elasticsearch_bootstrap_pw
#  when: stat_password.stat.exists
#
#- set_fact:
#    elasticsearch_bootstrap_pw = {{ pw_generated_elasticsearch_bootstrap_pw.stdout }}
#  when: pw_generated_elasticsearch_bootstrap_pw is defined
#
#- name: elasticsearch_bootstrap_pw genpw
#  shell:
#    cmd: cat /proc/sys/kernel/random/uuid | sed 's/[-]//g' | head -c 20; echo;
#  register: register_elasticsearch_bootstrap_pw
#  when: elasticsearch_bootstrap_pw is undefined
#
#- set_fact:
#    elasticsearch_bootstrap_pw = {{ register_elasticsearch_bootstrap_pw.stdout }}
#  when: register_elasticsearch_bootstrap_pw is defined
#
#- name: Password Generation - Check if the Password File exists
#  file:
#    path: /usr/share/elasticsearch/generated_passwords
#    state: file
#  when: not stat_password.stat.exists
#
#- name: Password Generation - Create the Password File
#  lineinfile:
#    path: /usr/share/elasticsearch/generated_passwords
#    line: 'elastic_boostrap_pw:{{elasticsearch_bootstrap_pw}}'
#    regexp: '^elastic_booststrap_pw'
#    state: present
#    backup: yes
#
##- debug: var=register_elasticsearch_bootstrap_pw
##- fail: 

# Sharing Shell Version Idea
- name: Generate bootstrap password
  shell: |
    if [ -f "/usr/share/elasticsearch/generated_passwords" ]; then
      password=$(grep "elasticsearch_bootstrap_pw" /usr/share/elasticsearch/generated_passwords | cut -d: -f2)
    else
      password=$(cat /proc/sys/kernel/random/uuid | tr -d '-' | head -c 20)
      echo "elastic_boostrap_pw:$password" > /usr/share/elasticsearch/generated_passwords
    fi
  register: result

- set_fact:
    elasticsearch_bootstrap_pw: "{{ result.stdout }}"