---

- name: Wait for instance
  ansible.builtin.wait_for:
    host: "{{ hostvars[item].ansible_default_ipv4.address }}"
    port: "{{ elasticstack_elasticsearch_http_port }}"
    timeout: 600
  tags:
    - certificates
    - renew_ca
    - renew_es_cert
