roles:
  logstash_custom_admin:
    cluster: ['manage_logstash_pipelines']
    indices:
      - names: ['.logstash*']
        privileges: ['create', 'delete', 'index', 'manage', 'read']
    metadata: {}
    run_as: []
  bugs_bunny:
    cluster: ['manage_logstash_pipelines']
    indices:
      - names: ['.logstash*']
        privileges: ['index', 'manage', 'read']
    metadata: {}
    run_as: []
  editor_like:
    applications:
      - application: "kibana-.kibana"
        privileges: ["all"]
        resources: ["*"]
    cluster: []
    indices:
      - allow_restricted_indices: false
        names: ['/~(([.]|ilm-history-).*)/']
        privileges: ['read']
      - allow_restricted_indices: false
        names: ['observability-annotations']
        privileges: ['read', 'view_index_metadata', 'write']
    metadata: {}
    run_as: []
