---
# The workaround for arbitrarily named role directory is important because
# the git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  vars:
    elastic_stack_full_stack: true
  tasks:
    - name: Include Elastic Repos
      include_role:
        name: repos
    - name: Include Elasticsearch role
      include_role:
        name: elasticsearch
    - name: Include logstash
      include_role:
        name: logstash
    - name: Include Kibana
      include_role:
        name: kibana
