---
- name: Prepare
  hosts: all
  tasks:
    - name: Install git
      package:
        name: git
    - name: Install gpg
      package:
        name: gpg
      when: ansible_os_family == "Debian"
    - name: Install procps
      package:
        name: procps
      when: ansible_os_family == "Debian"
