---

- name: Check if Logstash configuration does what it should
  hosts: all
  vars:
    elasticstack_release: "{{ lookup('env', 'ELASTIC_RELEASE') | int}}"
  tasks:
    - name: fetch Filebeat version
      ansible.builtin.command: "filebeat version | grep ^filebeat"
      register: beats_filebeat_version

    - name: DEBUG show filebeat version output
      ansible.builtin.debug:
        var: beats_filebeat_version.stdout

    - name: Fail if Filebeat has the wrong version
      ansible.builtin.fail:
        msg: "Filebeat has the wrong version"
      when:
        - beats_filebeat_version.stdout.find('7.17.1') == -1
        - elasticstack_release == 7

    - name: Fail if Filebeat has the wrong version
      ansible.builtin.fail:
        msg: "Filebeat has the wrong version"
      when:
        - beats_filebeat_version.stdout.find('8.4.1') == -1
        - elasticstack_release == 8

    - name: Ensure field is set correctly
      ansible.builtin.lineinfile:
        dest: /etc/filebeat/filebeat.yml
        line: "    testfield: thisisatest"
      check_mode: true
      register: _field
      failed_when: _field.changed
