---
galaxy_info:
  role_name: beats
  namespace: netways
  author: Thomas Widhalm <thomas.widhalm@netways.de>
  description: Beats for Linux
  company: "Netways GmbH"
  license: GPL-3.0-or-later
  min_ansible_version: "2.4"
  platforms:
    - name: EL
      versions:
        - "8"
    - name: Debian
      versions:
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - elk
    - beats
    - logging
    - system
dependencies: []
