---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  vars:
    elastic_stack_full_stack: true
    filebeat_syslog_udp: true
    filebeat_syslog_tcp: true
    filebeat_modules:
      - system
    beats_fields:
      - "testbed: molecule"
    elasticsearch_jna_workaround: true
    elasticsearch_disable_systemcallfilterchecks: true
  tasks:
    - name: "Include Elastics repos role"
      include_role:
        name: elastic-repos
    - name: Install rsyslog
      package:
        name: rsyslog
    - name: Start rsyslog
      service:
        name: rsyslog
        state: started
    - name: "Include Elasticsearch role"
      include_role:
        name: elasticsearch
    - name: "Include Redis"
      include_role:
        name: geerlingguy.redis
    - name: "Include Logstash"
      include_role:
        name: logstash
    - name: "Include Beats"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    - name: Configure rsyslog
      lineinfile:
        line: "*.* @@localhost:514"
        path: /etc/rsyslog.conf
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
      changed_when: false
