---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: beats_full_${MOLECULE_DISTRO:-centos7}
    groups:
      - elasticsearch
      - logstash
      - filebeat
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
