---
- name: elastic-repos
  src: https://github.com/widhalmt/ansible-role-elastic-repos
  scm: git
- name: elasticsearch
  src: https://github.com/widhalmt/ansible-role-elasticsearch.git
  scm: git
- name: beats
  src: https://github.com/widhalmt/ansible-role-beats.git
  scm: git
- src: geerlingguy.redis
