---
# This is an example playbook to execute Ansible tests.

- name: Check if Logstash configuration does what it should
  hosts: all
  tasks:
  - name: Run syntax check
    command: "/usr/share/logstash/bin/logstash --path.settings=/etc/logstash -t"
    when: "'logstash' in group_names"
  - name: Check for open port 5044/tcp
    wait_for:
      port: 5044
    when: "'logstash' in group_names"
