---
- name: Bootstrap Python 3.9 on Rocky Linux 8
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python 3.9 if not yet available (Rocky Linux 8)
      ansible.builtin.raw: |
        grep -qs "Rocky Linux release 8" /etc/redhat-release && dnf install -y python39 || true
      changed_when: false

- name: Prepare
  hosts: all
  tasks:
    - name: Install packages for Debian
      ansible.builtin.apt:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
          - git
          - openssl
          - python3
        update_cache: yes

    - name: Install python module dependencies
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - elasticsearch
