---
name: Test Collection Roles
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
  merge_group:

jobs:
  lint_full:
    uses: ./.github/workflows/test_linting.yml
    with:
      rolename: ''

  molecule_full_stack:
    runs-on: ubuntu-latest
    needs: lint_full

    env:
      COLLECTION_NAMESPACE: netways
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      matrix:
        distro:
          - rockylinux8
          - rockylinux9
          - ubuntu2204
        scenario:
          - elasticstack_default
        release:
          - 7
          - 8

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Python 3.8
        uses: actions/setup-python@v6
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-test.txt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a ../ansible-collection-$COLLECTION_NAME ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with molecule
        run: |
          molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ELASTIC_RELEASE: ${{ matrix.release }}
