---
name: Test Collection Roles
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/**'
      - '.github/workflows/test_roles_pr.yml'
      - 'molecule/elasticstack_default/**'
      - '.config/ansible-lint.yml'
      - '.yamllint'
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/**'
      - '.github/workflows/test_roles_pr.yml'
      - 'molecule/elasticstack_default/**'
      - '.config/ansible-lint.yml'
      - '.yamllint'

jobs:
  lint_full:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-test.txt

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint roles/
  molecule_full_stack:
    runs-on: ubuntu-latest
    needs: lint_full

    env:
      COLLECTION_NAMESPACE: netways
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        distro:
          - ubuntu2204
          - rockylinux8
        scenario:
          - elasticstack_default
        release:
          - 7
          - 8

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-test.txt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a ../ansible-collection-$COLLECTION_NAME ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 8
          max_attempts: 4
          retry_on: error
          command: |
            molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ELASTIC_RELEASE: ${{ matrix.release }}

#      - name: Test with molecule
#        run: |
#          molecule test -s ${{ matrix.scenario }}
#        env:
#          MOLECULE_DISTRO: ${{ matrix.distro }}
#          PY_COLORS: '1'
#          ANSIBLE_FORCE_COLOR: '1'
#          ELASTIC_RELEASE: ${{ matrix.release }}
