---
name: Test Role Kibana
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/kibana/**'
      - '.github/workflows/test_role_kibana.yml'
      - 'molecule/kibana_**'
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/kibana/**'
      - '.github/workflows/test_role_kibana.yml'
      - 'molecule/kibana_**'

jobs:
  lint_kibana:
    uses: ./.github/workflows/test_linting.yml
    with:
      rolename: kibana


  molecule_kibana:
    needs: lint_kibana
    runs-on: ubuntu-latest

    env:
      COLLECTION_NAMESPACE: NETWAYS
      COLLECTION_NAME: elasticstack

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        distro: [ubuntu2204]
        scenario: [kibana_default]
        release: [ 7, 8 ]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-test.txt

      - name: Install collection
        run: |
          mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          cp -a ../ansible-collection-$COLLECTION_NAME ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: Test with molecule
        run: |
          molecule test -s ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          ELASTIC_RELEASE: ${{ matrix.release }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
